"""
This type stub file was generated by pyright.
"""

from .base import XmlEnumeration, alias

"""
Enumerations related to the main document in WordprocessingML files
"""
@alias('WD_HEADER_FOOTER')
class WD_HEADER_FOOTER_INDEX(XmlEnumeration):
    """
    alias: **WD_HEADER_FOOTER**

    Specifies one of the three possible header/footer definitions for a section.

    For internal use only; not part of the python-docx API.
    """
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...

WD_HEADER_FOOTER = WD_HEADER_FOOTER_INDEX


@alias('WD_ORIENT')
class WD_ORIENTATION(XmlEnumeration):
    """
    alias: **WD_ORIENT**

    Specifies the page layout orientation.

    Example::

        from docx.enum.section import WD_ORIENT

        section = document.sections[-1]
        section.orientation = WD_ORIENT.LANDSCAPE
    """
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...

WD_ORIENT = WD_ORIENTATION

@alias('WD_SECTION')
class WD_SECTION_START(XmlEnumeration):
    """
    alias: **WD_SECTION**

    Specifies the start type of a section break.

    Example::

        from docx.enum.section import WD_SECTION

        section = document.sections[0]
        section.start_type = WD_SECTION.NEW_PAGE
    """
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...

WD_SECTION = WD_SECTION_START

