"""
This type stub file was generated by pyright.
"""

from .base import XmlEnumeration, alias

"""
Enumerations related to text in WordprocessingML files
"""
@alias('WD_ALIGN_PARAGRAPH')
class WD_PARAGRAPH_ALIGNMENT(XmlEnumeration):
    """
    alias: **WD_ALIGN_PARAGRAPH**

    Specifies paragraph justification type.

    Example::

        from docx.enum.text import WD_ALIGN_PARAGRAPH

        paragraph = document.add_paragraph()
        paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    """
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...

WD_ALIGN_PARAGRAPH = WD_PARAGRAPH_ALIGNMENT

class WD_BREAK_TYPE:
    """
    Corresponds to WdBreakType enumeration
    http://msdn.microsoft.com/en-us/library/office/ff195905.aspx
    """
    COLUMN = ...
    LINE = ...
    LINE_CLEAR_LEFT = ...
    LINE_CLEAR_RIGHT = ...
    LINE_CLEAR_ALL = ...
    PAGE = ...
    SECTION_CONTINUOUS = ...
    SECTION_EVEN_PAGE = ...
    SECTION_NEXT_PAGE = ...
    SECTION_ODD_PAGE = ...
    TEXT_WRAPPING = ...


WD_BREAK = WD_BREAK_TYPE
@alias('WD_COLOR')
class WD_COLOR_INDEX(XmlEnumeration):
    """
    Specifies a standard preset color to apply. Used for font highlighting and
    perhaps other applications.
    """
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...

WD_COLOR = WD_COLOR_INDEX

class WD_LINE_SPACING(XmlEnumeration):
    """
    Specifies a line spacing format to be applied to a paragraph.

    Example::

        from docx.enum.text import WD_LINE_SPACING

        paragraph = document.add_paragraph()
        paragraph.line_spacing_rule = WD_LINE_SPACING.EXACTLY
    """
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


class WD_TAB_ALIGNMENT(XmlEnumeration):
    """
    Specifies the tab stop alignment to apply.
    """
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


class WD_TAB_LEADER(XmlEnumeration):
    """
    Specifies the character to use as the leader with formatted tabs.
    """
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


class WD_UNDERLINE(XmlEnumeration):
    """
    Specifies the style of underline applied to a run of characters.
    """
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


