"""
This type stub file was generated by pyright.
"""

from .base import Enumeration, XmlEnumeration, alias

"""
Enumerations used by DrawingML objects
"""
class MSO_COLOR_TYPE(Enumeration):
    """
    Specifies the color specification scheme

    Example::

        from docx.enum.dml import MSO_COLOR_TYPE

        assert font.color.type == MSO_COLOR_TYPE.SCHEME
    """
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


@alias('MSO_THEME_COLOR')
class MSO_THEME_COLOR_INDEX(XmlEnumeration):
    """
    Indicates the Office theme color, one of those shown in the color gallery
    on the formatting ribbon.

    Alias: ``MSO_THEME_COLOR``

    Example::

        from docx.enum.dml import MSO_THEME_COLOR

        font.color.theme_color = MSO_THEME_COLOR.ACCENT_1
    """
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...

MSO_THEME_COLOR = MSO_THEME_COLOR_INDEX

