"""
This type stub file was generated by pyright.
"""

"""
Enumerations related to DrawingML shapes in WordprocessingML files
"""
class WD_INLINE_SHAPE_TYPE:
    """
    Corresponds to WdInlineShapeType enumeration
    http://msdn.microsoft.com/en-us/library/office/ff192587.aspx
    """
    CHART = ...
    LINKED_PICTURE = ...
    PICTURE = ...
    SMART_ART = ...
    NOT_IMPLEMENTED = ...


WD_INLINE_SHAPE = WD_INLINE_SHAPE_TYPE
