"""
This type stub file was generated by pyright.
"""

import sys

"""
Provides Python 2/3 compatibility objects
"""
if sys.version_info >= (3, 0):
    def is_string(obj) -> bool:
        """Return True if *obj* is a string, False otherwise."""
        ...
    
    Unicode = str
else:
    ...
