"""
This type stub file was generated by pyright.
"""

from docx.shared import ElementProxy

"""Settings object, providing access to document-level settings"""
class Settings(ElementProxy):
    """Provides access to document-level settings for a document.

    Accessed using the :attr:`.Document.settings` property.
    """
    __slots__ = ...
    @property
    def odd_and_even_pages_header_footer(self):
        """True if this document has distinct odd and even page headers and footers.

        Read/write.
        """
        ...
    
    @odd_and_even_pages_header_footer.setter
    def odd_and_even_pages_header_footer(self, value): # -> None:
        ...
    


