"""
This type stub file was generated by pyright.
"""

from .shared import Parented

"""
Objects related to shapes, visual objects that appear on the drawing layer of
a document.
"""
class InlineShapes(Parented):
    """
    Sequence of |InlineShape| instances, supporting len(), iteration, and
    indexed access.
    """
    def __init__(self, body_elm, parent) -> None:
        ...
    
    def __getitem__(self, idx): # -> InlineShape:
        """
        Provide indexed access, e.g. 'inline_shapes[idx]'
        """
        ...
    
    def __iter__(self): # -> Generator[InlineShape, None, None]:
        ...
    
    def __len__(self): # -> int:
        ...
    


class InlineShape:
    """
    Proxy for an ``<wp:inline>`` element, representing the container for an
    inline graphical object.
    """
    def __init__(self, inline) -> None:
        ...
    
    @property
    def height(self):
        """
        Read/write. The display height of this inline shape as an |Emu|
        instance.
        """
        ...
    
    @height.setter
    def height(self, cy): # -> None:
        ...
    
    @property
    def type(self): # -> Literal[4, 3, 12, 15, -6]:
        """
        The type of this inline shape as a member of
        ``docx.enum.shape.WD_INLINE_SHAPE``, e.g. ``LINKED_PICTURE``.
        Read-only.
        """
        ...
    
    @property
    def width(self):
        """
        Read/write. The display width of this inline shape as an |Emu|
        instance.
        """
        ...
    
    @width.setter
    def width(self, cx): # -> None:
        ...
    


