"""
This type stub file was generated by pyright.
"""

from docx.oxml.xmlchemy import BaseOxmlElement

"""Custom element classes related to document settings"""
class CT_Settings(BaseOxmlElement):
    """`w:settings` element, root element for the settings part"""
    _tag_seq = ...
    evenAndOddHeaders = ...
    @property
    def evenAndOddHeaders_val(self): # -> Literal[False]:
        """value of `w:evenAndOddHeaders/@w:val` or |None| if not present."""
        ...
    
    @evenAndOddHeaders_val.setter
    def evenAndOddHeaders_val(self, value): # -> None:
        ...
    


