"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import, division, print_function, unicode_literals

"""
Sub-package module for docx.styles sub-package.
"""
class BabelFish:
    """
    Translates special-case style names from UI name (e.g. Heading 1) to
    internal/styles.xml name (e.g. heading 1) and back.
    """
    style_aliases = ...
    internal_style_names = ...
    ui_style_names = ...
    @classmethod
    def ui2internal(cls, ui_style_name): # -> Literal['caption', 'footer', 'header', 'heading 1', 'heading 2', 'heading 3', 'heading 4', 'heading 5', 'heading 6', 'heading 7', 'heading 8', 'heading 9']:
        """
        Return the internal style name corresponding to *ui_style_name*, such
        as 'heading 1' for 'Heading 1'.
        """
        ...
    
    @classmethod
    def internal2ui(cls, internal_style_name): # -> Literal['Caption', 'Footer', 'Header', 'Heading 1', 'Heading 2', 'Heading 3', 'Heading 4', 'Heading 5', 'Heading 6', 'Heading 7', 'Heading 8', 'Heading 9']:
        """
        Return the user interface style name corresponding to
        *internal_style_name*, such as 'Heading 1' for 'heading 1'.
        """
        ...
    


