"""
This type stub file was generated by pyright.
"""

from ..shared import ElementProxy

"""
Font-related proxy objects.
"""
class Font(ElementProxy):
    """
    Proxy object wrapping the parent of a ``<w:rPr>`` element and providing
    access to character properties such as font name, font size, bold, and
    subscript.
    """
    __slots__ = ...
    @property
    def all_caps(self): # -> None:
        """
        Read/write. Causes text in this font to appear in capital letters.
        """
        ...
    
    @all_caps.setter
    def all_caps(self, value): # -> None:
        ...
    
    @property
    def bold(self): # -> None:
        """
        Read/write. Causes text in this font to appear in bold.
        """
        ...
    
    @bold.setter
    def bold(self, value): # -> None:
        ...
    
    @property
    def color(self): # -> ColorFormat:
        """
        A |ColorFormat| object providing a way to get and set the text color
        for this font.
        """
        ...
    
    @property
    def complex_script(self): # -> None:
        """
        Read/write tri-state value. When |True|, causes the characters in the
        run to be treated as complex script regardless of their Unicode
        values.
        """
        ...
    
    @complex_script.setter
    def complex_script(self, value): # -> None:
        ...
    
    @property
    def cs_bold(self): # -> None:
        """
        Read/write tri-state value. When |True|, causes the complex script
        characters in the run to be displayed in bold typeface.
        """
        ...
    
    @cs_bold.setter
    def cs_bold(self, value): # -> None:
        ...
    
    @property
    def cs_italic(self): # -> None:
        """
        Read/write tri-state value. When |True|, causes the complex script
        characters in the run to be displayed in italic typeface.
        """
        ...
    
    @cs_italic.setter
    def cs_italic(self, value): # -> None:
        ...
    
    @property
    def double_strike(self): # -> None:
        """
        Read/write tri-state value. When |True|, causes the text in the run
        to appear with double strikethrough.
        """
        ...
    
    @double_strike.setter
    def double_strike(self, value): # -> None:
        ...
    
    @property
    def emboss(self): # -> None:
        """
        Read/write tri-state value. When |True|, causes the text in the run
        to appear as if raised off the page in relief.
        """
        ...
    
    @emboss.setter
    def emboss(self, value): # -> None:
        ...
    
    @property
    def hidden(self): # -> None:
        """
        Read/write tri-state value. When |True|, causes the text in the run
        to be hidden from display, unless applications settings force hidden
        text to be shown.
        """
        ...
    
    @hidden.setter
    def hidden(self, value): # -> None:
        ...
    
    @property
    def highlight_color(self): # -> None:
        """
        A member of :ref:`WdColorIndex` indicating the color of highlighting
        applied, or `None` if no highlighting is applied.
        """
        ...
    
    @highlight_color.setter
    def highlight_color(self, value): # -> None:
        ...
    
    @property
    def italic(self): # -> None:
        """
        Read/write tri-state value. When |True|, causes the text of the run
        to appear in italics. |None| indicates the effective value is
        inherited from the style hierarchy.
        """
        ...
    
    @italic.setter
    def italic(self, value): # -> None:
        ...
    
    @property
    def imprint(self): # -> None:
        """
        Read/write tri-state value. When |True|, causes the text in the run
        to appear as if pressed into the page.
        """
        ...
    
    @imprint.setter
    def imprint(self, value): # -> None:
        ...
    
    @property
    def math(self): # -> None:
        """
        Read/write tri-state value. When |True|, specifies this run contains
        WML that should be handled as though it was Office Open XML Math.
        """
        ...
    
    @math.setter
    def math(self, value): # -> None:
        ...
    
    @property
    def name(self): # -> None:
        """
        Get or set the typeface name for this |Font| instance, causing the
        text it controls to appear in the named font, if a matching font is
        found. |None| indicates the typeface is inherited from the style
        hierarchy.
        """
        ...
    
    @name.setter
    def name(self, value): # -> None:
        ...
    
    @property
    def no_proof(self): # -> None:
        """
        Read/write tri-state value. When |True|, specifies that the contents
        of this run should not report any errors when the document is scanned
        for spelling and grammar.
        """
        ...
    
    @no_proof.setter
    def no_proof(self, value): # -> None:
        ...
    
    @property
    def outline(self): # -> None:
        """
        Read/write tri-state value. When |True| causes the characters in the
        run to appear as if they have an outline, by drawing a one pixel wide
        border around the inside and outside borders of each character glyph.
        """
        ...
    
    @outline.setter
    def outline(self, value): # -> None:
        ...
    
    @property
    def rtl(self): # -> None:
        """
        Read/write tri-state value. When |True| causes the text in the run
        to have right-to-left characteristics.
        """
        ...
    
    @rtl.setter
    def rtl(self, value): # -> None:
        ...
    
    @property
    def shadow(self): # -> None:
        """
        Read/write tri-state value. When |True| causes the text in the run
        to appear as if each character has a shadow.
        """
        ...
    
    @shadow.setter
    def shadow(self, value): # -> None:
        ...
    
    @property
    def size(self): # -> None:
        """
        Read/write |Length| value or |None|, indicating the font height in
        English Metric Units (EMU). |None| indicates the font size should be
        inherited from the style hierarchy. |Length| is a subclass of |int|
        having properties for convenient conversion into points or other
        length units. The :class:`docx.shared.Pt` class allows convenient
        specification of point values::

            >> font.size = Pt(24)
            >> font.size
            304800
            >> font.size.pt
            24.0
        """
        ...
    
    @size.setter
    def size(self, emu): # -> None:
        ...
    
    @property
    def small_caps(self): # -> None:
        """
        Read/write tri-state value. When |True| causes the lowercase
        characters in the run to appear as capital letters two points smaller
        than the font size specified for the run.
        """
        ...
    
    @small_caps.setter
    def small_caps(self, value): # -> None:
        ...
    
    @property
    def snap_to_grid(self): # -> None:
        """
        Read/write tri-state value. When |True| causes the run to use the
        document grid characters per line settings defined in the docGrid
        element when laying out the characters in this run.
        """
        ...
    
    @snap_to_grid.setter
    def snap_to_grid(self, value): # -> None:
        ...
    
    @property
    def spec_vanish(self): # -> None:
        """
        Read/write tri-state value. When |True|, specifies that the given run
        shall always behave as if it is hidden, even when hidden text is
        being displayed in the current document. The property has a very
        narrow, specialized use related to the table of contents. Consult the
        spec (§17.3.2.36) for more details.
        """
        ...
    
    @spec_vanish.setter
    def spec_vanish(self, value): # -> None:
        ...
    
    @property
    def strike(self): # -> None:
        """
        Read/write tri-state value. When |True| causes the text in the run
        to appear with a single horizontal line through the center of the
        line.
        """
        ...
    
    @strike.setter
    def strike(self, value): # -> None:
        ...
    
    @property
    def subscript(self): # -> None:
        """
        Boolean indicating whether the characters in this |Font| appear as
        subscript. |None| indicates the subscript/subscript value is
        inherited from the style hierarchy.
        """
        ...
    
    @subscript.setter
    def subscript(self, value): # -> None:
        ...
    
    @property
    def superscript(self): # -> None:
        """
        Boolean indicating whether the characters in this |Font| appear as
        superscript. |None| indicates the subscript/superscript value is
        inherited from the style hierarchy.
        """
        ...
    
    @superscript.setter
    def superscript(self, value): # -> None:
        ...
    
    @property
    def underline(self): # -> None:
        """
        The underline style for this |Font|, one of |None|, |True|, |False|,
        or a value from :ref:`WdUnderline`. |None| indicates the font
        inherits its underline value from the style hierarchy. |False|
        indicates no underline. |True| indicates single underline. The values
        from :ref:`WdUnderline` are used to specify other outline styles such
        as double, wavy, and dotted.
        """
        ...
    
    @underline.setter
    def underline(self, value): # -> None:
        ...
    
    @property
    def web_hidden(self): # -> None:
        """
        Read/write tri-state value. When |True|, specifies that the contents
        of this run shall be hidden when the document is displayed in web
        page view.
        """
        ...
    
    @web_hidden.setter
    def web_hidden(self, value): # -> None:
        ...
    


